site_name: PyQuran
theme: 'readthedocs'
docs_dir: docs
repo_url: https://github.com/hci-lab/pyquran-private


pages:
- Hello World!:
    - Home: 'index.md'
- Users Documentation:
    - Basic Tools for Quran: 'quran_tools.md'
    - Arabic Tools: 'arabic_tools.md'
    - Analysis Tools: 'analysis_tools.md'
- Maintainers:
    - Getting Started: 'CONTRIBUTING.md'
    - Package Strucutre: 'Wiki-Home.md'
    - Quran Corpus: 'Filtering-Special-Recitation-Symbols.md'
    - Code Conventios: 'code_conventions.md'
